### ISSUE TITLE
图标失效

### ISSUE THREAD

**Issue by 201405kpb** [yudaocode/yudao-ui-admin-vben#1]
菜单图标无效

**Comment by YunaiV** [comment]
https://gitee.com/yudaocode/yudao-ui-admin-vben
辛苦提到这里哈

**Comment by 201405kpb** [comment]
![1687228433825](https://github.com/yudaocode/yudao-ui-admin-vben/assets/8186801/26043e41-8c3e-46b2-b88f-3162eb0d7ad0)

**Comment by 201405kpb** [comment]
我指的是用户管理前面的图标

**Comment by xingyuv** [comment]
> 我指的是用户管理前面的图标

vue2 vue3 不兼容，目前的菜单依然用的vue2的
