### ISSUE TITLE
Vue3 + vben(ant-design-vue) 表单设计器有bug

### ISSUE THREAD

**Issue by Luyg88** [yudaocode/yudao-ui-admin-vben#3]
![af75bf32f64c363b8ad5d347dd0e5aa](https://github.com/yudaocode/yudao-ui-admin-vben/assets/150045403/0dabbb3a-7c3e-40c0-8217-f3457b6ce145)
芋道Vue3 + vben(ant-design-vue) 前端PC端代码，表单设计器有bug，右边状态栏无法显示出来，并且表单管理新增功能点击没反应

**Comment by YunaiV** [comment]
预计 v2.3.0 会解决。

**Comment by YunaiV** [comment]
已修复

**Comment by YunaiV** [comment]
估计 2.2.0 发布就带上了
